### ISSUE TITLE
Map of -,+

### ISSUE THREAD

**Issue by Rekvia** [gipsy-king/civmap-journeymap#4]
Hi, I'd like for Requiem to be added to txapu. The needed information is below.

Type: City

Name: Requiem

Coordinates: -5282, 3664

Flag: http://i.imgur.com/LqWQGcF.png?1

Reddit: /r/CivRequiem (Currently private)

Desired two-letter code: RQ, or if possible, Req

Once it is on the map I will be making a pull request for the land claims. Thank you

**Comment by gipsy-king** [comment]
added
