### ISSUE TITLE
Journeymap no like Flan's mod

### ISSUE THREAD

**Issue by border999** [gipsy-king/civmap-journeymap#5]
I had just deleted my color palette file due to changing around and removing multiple mods. The only mod I added was Flan's, upon generating a world it crashes with an error of the mod attempting to get textures.
If you'll look into this issue both are the latest versions for 1.7.10.
If you need to know later on what version of your mod I'm talking about, reference the date this was posted.

**Comment by gipsy-king** [comment]
Sorry this repo has nothing to do with client mods.
